[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.17.1",features = ["blas"] }
blas-src = { version = "0.14", features = ["openblas"] }
openblas-src = { version = "0.10", features = ["cblas", "system"] }
macroquad = "0.4"

